package org.gemusi.system.model;

import java.util.Date;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_user.id
     *
     * @mbg.generated Mon Dec 17 15:34:44 GMT+08:00 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_user.userid
     *
     * @mbg.generated Mon Dec 17 15:34:44 GMT+08:00 2018
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_user.username
     *
     * @mbg.generated Mon Dec 17 15:34:44 GMT+08:00 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_user.password
     *
     * @mbg.generated Mon Dec 17 15:34:44 GMT+08:00 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_user.mobile
     *
     * @mbg.generated Mon Dec 17 15:34:44 GMT+08:00 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_user.email
     *
     * @mbg.generated Mon Dec 17 15:34:44 GMT+08:00 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_user.note
     *
     * @mbg.generated Mon Dec 17 15:34:44 GMT+08:00 2018
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_user.createtime
     *
     * @mbg.generated Mon Dec 17 15:34:44 GMT+08:00 2018
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_user.id
     *
     * @return the value of tb_sys_user.id
     *
     * @mbg.generated Mon Dec 17 15:34:44 GMT+08:00 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_user.id
     *
     * @param id the value for tb_sys_user.id
     *
     * @mbg.generated Mon Dec 17 15:34:44 GMT+08:00 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_user.userid
     *
     * @return the value of tb_sys_user.userid
     *
     * @mbg.generated Mon Dec 17 15:34:44 GMT+08:00 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_user.userid
     *
     * @param userid the value for tb_sys_user.userid
     *
     * @mbg.generated Mon Dec 17 15:34:44 GMT+08:00 2018
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_user.username
     *
     * @return the value of tb_sys_user.username
     *
     * @mbg.generated Mon Dec 17 15:34:44 GMT+08:00 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_user.username
     *
     * @param username the value for tb_sys_user.username
     *
     * @mbg.generated Mon Dec 17 15:34:44 GMT+08:00 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_user.password
     *
     * @return the value of tb_sys_user.password
     *
     * @mbg.generated Mon Dec 17 15:34:44 GMT+08:00 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_user.password
     *
     * @param password the value for tb_sys_user.password
     *
     * @mbg.generated Mon Dec 17 15:34:44 GMT+08:00 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_user.mobile
     *
     * @return the value of tb_sys_user.mobile
     *
     * @mbg.generated Mon Dec 17 15:34:44 GMT+08:00 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_user.mobile
     *
     * @param mobile the value for tb_sys_user.mobile
     *
     * @mbg.generated Mon Dec 17 15:34:44 GMT+08:00 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_user.email
     *
     * @return the value of tb_sys_user.email
     *
     * @mbg.generated Mon Dec 17 15:34:44 GMT+08:00 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_user.email
     *
     * @param email the value for tb_sys_user.email
     *
     * @mbg.generated Mon Dec 17 15:34:44 GMT+08:00 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_user.note
     *
     * @return the value of tb_sys_user.note
     *
     * @mbg.generated Mon Dec 17 15:34:44 GMT+08:00 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_user.note
     *
     * @param note the value for tb_sys_user.note
     *
     * @mbg.generated Mon Dec 17 15:34:44 GMT+08:00 2018
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_user.createtime
     *
     * @return the value of tb_sys_user.createtime
     *
     * @mbg.generated Mon Dec 17 15:34:44 GMT+08:00 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_user.createtime
     *
     * @param createtime the value for tb_sys_user.createtime
     *
     * @mbg.generated Mon Dec 17 15:34:44 GMT+08:00 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}